### ISSUE TITLE
Exception on where condition when accessing chromadb

### ISSUE THREAD

**Issue by a-rbts** [v2rockets/Loyal-Elephie#7]
There are a few failure cases where an exception is thrown after the first prompt, when no history is present.
One of them happens upon querying chromadb with a where condition on dates (the variables are called start_time and end_time but are actually dates without timestamps) because chromadb explicitly disallows comparisons on strings [here](https://github.com/chroma-core/chroma/blob/main/chromadb/api/types.py#L368). 

This makes queries generated [here](https://github.com/v2rockets/Loyal-Elephie/blob/main/backend/chroma_doc_manager.py#L93) to be improper since start_time_str (and end_time_str) are strings. 

The backend then immediately throws without possibility to recover.

**Comment by v2rockets** [comment]
Oh, this app need string comparisons but chromadb limits the gte/lte for only int and float. So I've modified the original chroma code, but it seems not wise for an open source project. So let me try update a "monkey patch" https://github.com/v2rockets/Loyal-Elephie/commit/ced7580edc9c01bbd4ffcec59532c570a5b37905 and see if it works!
